actuators:
  - package: dynamixel_x_controller
    class: Dynamixel_X::Dynamixel_X_Actuator_Config_Parser
    config:
      shoulder_lateral_actuator:
        servo_id: 1
        controller_name: sting_controller
        cw_limit_deg: -180.0
        ccw_limit_deg: 180.0
      sholder_vertical_actuator:
        servo_id: 2
        controller_name: sting_controller
        cw_limit_deg: -180.0
        ccw_limit_deg: 180.0
      elbow_actuator:
        servo_id: 3
        controller_name: sting_controller
        cw_limit_deg: -180.0
        ccw_limit_deg: 180.0
      lower_arm_yaw_actuator:
        servo_id: 4
        controller_name: sting_controller
        cw_limit_deg: -180.0
        ccw_limit_deg: 180.0
      lower_arm_vertical_actuator:
        servo_id: 5
        controller_name: sting_controller
        cw_limit_deg: -180.0
        ccw_limit_deg: 180.0
      gripper_yaw_actuator:
        servo_id: 6
        controller_name: sting_controller
        cw_limit_deg: -180.0
        ccw_limit_deg: 180.0

controllers:
  - package: dynamixel_x_controller
    class: Dynamixel_X::Dynamixel_X_Controller_Config_Parser
    config:
      sting_controller:
        controller_id: 1
        port: /dev/u2d2
        baud_rate: 57600
