joints:
  shoulder_lateral:
    type: PositionControlledJoint
    default_rpm: 20.0
  sholder_vertical:
    type: PositionControlledJoint
    default_rpm: 20.0
  elbow:
    type: PositionControlledJoint
    default_rpm: 20.0
  lower_arm_yaw:
    type: PositionControlledJoint
    default_rpm: 20.0
  lower_arm_vertical:
    type: PositionControlledJoint
    default_rpm: 20.0
  gripper_yaw:
    type: PositionControlledJoint
    default_rpm: 20.0

