sting_arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - shoulder_lateral
    - sholder_vertical
    - elbow
    - lower_arm_yaw
    - lower_arm_vertical
    - gripper_yaw
  gains:
    shoulder_lateral:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    sholder_vertical:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    elbow:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    lower_arm_yaw:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    lower_arm_vertical:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    gripper_yaw:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
